{application,test_divi,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{test_divi_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[test_divi_app,test_divi_server,test_divi_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
